const UserActionType  ={
    LOG_IN_USER: 'LOG_IN_USER',
    SET_EMAIL_PASS_LOG_IN: 'SET_EMAIL_PASS_LOG_IN',
    SET_USER_SIGNUP: 'SET_USER_SIGNUP',
    GET_USERS_LIST: 'GET_USERS_LIST',
    GET_PERMISSIONS_USERS: 'GET_PERMISSIONS_USERS',
    SET_USERS_WITH_PERMISSIONS: 'SET_USERS_WITH_PERMISSIONS',
    GET_USERS_LOGIN_LIST: 'GET_USERS_LOGIN_LIST'
}

export default UserActionType;